config/routes.rb
Lodgerapp::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	devise_for :users, :skip => [:registrations] 
	as :user do
		get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
		put 'users' => 'devise/registrations#update', :as => 'user_registration'
	end
	root to: "properties#index"

	resources :properties do
		get 'vacant', :on => :collection
		resources :tenants
	end

	resources :tenants do
		get 'current', :on => :collection
	end
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
	include IceCube

	validates :first_name, :second_name, :rent_start_date, :presence => true
	validates :house_phone, :mobile_phone, :length => {:minimum => 9, :maximum => 15}, :format => { :with => /\A\S[0-9\+\/\(\)\s\-]*\z/i }, :allow_blank => true
	validates :email, :format => { :with => /\A[^@]+@[^@]+\z/ }, :allow_blank => true

	mount_uploader :tenancy_agreement, DocumentUploader

	belongs_to :property
	has_one :payment, :dependent => :destroy

	accepts_nested_attributes_for :payment

	def weekly
		schedule = Schedule.new(rent_start_date.to_time)
		schedule.add_recurrence_time(Time.now)
		schedule.add_recurrence_rule Rule.weekly
		schedule.next_occurrence
	end

	def fortnightly
		schedule = Schedule.new(rent_start_date.to_time)
		schedule.add_recurrence_time(Time.now)
		schedule.add_recurrence_rule Rule.weekly(2)
		schedule.next_occurrence
	end

	def monthly
		schedule = Schedule.new(rent_start_date.to_time)
		schedule.add_recurrence_time(Time.now)
		schedule.add_recurrence_rule Rule.monthly
		schedule.next_occurrence
	end

	def rent_due_in_weekly
		d = Date.today.strftime("%e %b %Y")
		e = weekly.strftime("%e %b %Y")
		now = Date.parse(d)
		due = Date.parse(e)
		(due - now).to_i		
	end

	def rent_due_in
		d = Date.today.strftime("%e %b %Y")
		e = fortnightly.strftime("%e %b %Y")
		now = Date.parse(d)
		due = Date.parse(e)
		(due - now).to_i
	end
    
	def rent_due_in_monthly
		d = Date.today.strftime("%e %b %Y")
		e = monthly.strftime("%e %b %Y")
		now = Date.parse(d)
		due = Date.parse(e)
		(due - now).to_i
	end

	def one_monthly
	unless rent_start_date.future?
		schedule = Schedule.new(rent_start_date.to_time)
		schedule.add_recurrence_rule Rule.monthly
		schedule.next_occurrence
	else
		skip_first_occurrence = rent_start_date + 1.month
		schedule = Schedule.new(skip_first_occurrence.to_time)
		schedule.add_recurrence_rule Rule.monthly
		schedule.next_occurrence
	end
	end

	def half_year
	unless rent_start_date.future?
		schedule = Schedule.new(rent_start_date.to_time)
		schedule.add_recurrence_rule Rule.monthly(6)
		schedule.next_occurrence
	else
		skip_first_occurrence = rent_start_date + 6.months
		schedule = Schedule.new(skip_first_occurrence.to_time)
		schedule.add_recurrence_rule Rule.monthly(6)
		schedule.next_occurrence
	end
	end

	def yearly
	unless rent_start_date.future?
		schedule = Schedule.new(rent_start_date.to_time)
		schedule.add_recurrence_rule Rule.yearly
		schedule.next_occurrence
	else
		skip_first_occurrence = rent_start_date + 1.years
		schedule = Schedule.new(skip_first_occurrence.to_time)
		schedule.add_recurrence_rule Rule.yearly
		schedule.next_occurrence
	end
	end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
	before_filter :authenticate_user!

	set_tab :tenant, :only => %w(current)

	def new
		@property = Property.find(params[:property_id])
		@tenant = @property.tenants.build
		@tenant.build_payment
	end

	def create
		@property = Property.find(params[:property_id])
		@tenant = @property.tenants.build(app_params)
		if @tenant.save
			redirect_to property_tenant_path(@property, @tenant)
		else
			render('new')
		end
	end

	def show
		@property = Property.find(params[:property_id])
		@tenant = @property.tenants.find(params[:id])
	end

	def edit
		@property = Property.find(params[:property_id])
		@tenant = @property.tenants.find(params[:id])
	end

	def update
		@property = Property.find(params[:property_id])
		@tenant = @property.tenants.find(params[:id])
		if @tenant.update_attributes(app_params)
			redirect_to property_tenant_path(@property, @tenant)
		else
			render('edit')
		end
	end

	def destroy
		@tenant = Tenant.find(params[:id])
		@tenant.destroy
		redirect_to properties_path
	end

	def current
		@tenants = current_user.tenants.all
	end

	def app_params
		params.require(:tenant).permit(:first_name, :second_name, :house_phone, :mobile_phone, :email, :rent_start_date, :rent_frequency, :tenancy_term, :tenancy_agreement, payment_attributes: [:id, :rent_amount, :deposit, :deposit_received])
	end
end

app/helpers/tenants_helper.rb
module TenantsHelper
	def full_name(tenant)
		tenant.first_name + " " + tenant.second_name
	end

	def property_address(tenant)
		[tenant.property.house_number, tenant.property.street_address, tenant.property.street_address_two, tenant.property.city, tenant.property.postcode.upcase].compact.reject(&:blank?).join(', ')
	end

	def deposit_true_or_false(tenant)
		if tenant.payment.deposit_received == true
			"Yes"
		else
			"No"
		end
	end

	def rent_due_class_weekly(tenant)
	if tenant.rent_due_in_weekly <= 7
		return 'rent due-soon'
	else
		return 'rent due-distance'
	end
	end

	def rent_due_class_monthly(tenant)
	if tenant.rent_due_in_monthly <= 7
		return 'rent due-soon'
	else
		return 'rent due-distance'
	end
	end
  
	def rent_due_class_fortnightly(tenant)
	if tenant.rent_due_in_fortnightly <= 7
		return 'rent due-soon'
	else
		return 'rent due-distance'
	end
	end
end

app/views/tenants/_property_details.html.erb
<section class="full-property-details">
	<article class="property-address-list">
		<h2 class="beta page-title">Property Details</h2>
		<span class="address-line"><%= @property.house_number %>, <%= @property.street_address %>,</span>
		<% unless @property.street_address_two.blank? %>
		<span class="address-line"><%= @property.street_address_two %>,</span>
		<% end %>
		<span class="address-line"><%= @property.city %>,</span>
		<span class="address-line"><%= @property.postcode.upcase %></span>
		<%= link_to "[Edit]", edit_property_path(@property), :class => "edit edit-address", :title => "Edit address" %>
		<%= link_to "[Delete]", property_path(@property), :class => "delete edit", :method => 'delete', :data => { :confirm => "Are you sure?" } %>
	</article>
</section>

<hr class="divider" />

app/views/tenants/current.html.erb
<section class="current-tenants">
	<div class="current-tenants-management">
		<h2 class="beta properties-filter-title">Current Tenants (<%= @tenants.count %>)</h2>
	</div>
	
<% @tenants.each do |tenant| unless @tenants.blank? %>
	<article class="property">
		<div class="property-details">
		<div class="property-info">
			<h3 class="tenant-name"><%= link_to full_name(tenant), property_tenant_path(tenant.property, tenant) %></h3>
				<div class="property-address-current">
					<%= property_address(tenant) %>
				</div>
		</div>

		<div class="rent-info">
		<% if tenant.rent_frequency == "weekly" %>
			<span class="rent-due">Rent due in:</span>
			<span class="<%= rent_due_class_weekly(tenant) %>"><%= pluralize(tenant.rent_due_in_weekly, "day") %></span>
		<% end %>			
		<% if tenant.rent_frequency == "fortnightly" %>
			<span class="rent-due">Rent due in:</span>
			<span class="<%= rent_due_class_fortnightly(tenant) %>"><%= pluralize(tenant.rent_due_in_fortnightly, "day") %></span>
		<% end %>
		<% if tenant.rent_frequency == "monthly" %>
			<span class="rent-due">Rent due in:</span>
			<span class="<%= rent_due_class_monthly(tenant) %>"><%= pluralize(tenant.rent_due_in_monthly, "day") %></span>
		<% end %>
		</div>
		
		</div>
	</article>

<% end %>
<% end %>

<% if current_user.properties.empty? %>
	<p class="property-empty">Your tenant needs a property to live in. <%= link_to new_property_path(@property), :class => "button new-property" do %>
	<span class="icon add-new"></span><%= "Add property" %>
    
	<% end %>
	</p>
<% end %>

<% if current_user.properties.present? && @tenants.empty? %>
	<p class="property-empty">You haven't added any tenants yet. <%= link_to vacant_properties_path(@property), :class => "button new-property" do %>
	<span class="icon add-new"></span><%= "Add tenant" %>
	<% end %>
	</p>
<% end %>

</section>

app/views/tenants/edit.html.erb
<%= render 'property_details' %>

<section class="current-tenants">
	<div class="current-tenants-management">
		<h2 class="beta section-title">Current Tenant(s)</h2>
	</div>
	<div class="current-tenant">
		
	<h3 class="center">Enter tenant's details</h3>
	<%= form_for @tenant, :html => { :class => "tenant-details" }, :url => property_tenant_path(@property, @tenant) do |f| %>
	<%= render "shared/tenant_error_message", :target => @tenant %>
		
	<fieldset>
		<%= f.label :first_name, "First Name:" %>
		<%= f.text_field :first_name %>
	</fieldset>
	<fieldset>
		<%= f.label :second_name, "Surname:" %>
		<%= f.text_field :second_name %>
	</fieldset>
	<fieldset>
		<%= f.label :email, "Email:" %>
		<%= f.text_field :email %>
	</fieldset>
	<fieldset>
		<%= f.label :house_phone, "House Phone:" %>
		<%= f.text_field :house_phone %>
	</fieldset>
	<fieldset>
		<%= f.label :mobile_phone, "Mobile Phone:" %>
		<%= f.text_field :mobile_phone %>
	</fieldset>
<hr class="divider" />

<article class="tenant-agreement">
	<h3 class="beta agreement-title">Renting Agreement</h3>
		<div class="agreement-list">
			<div class="agreement">
				<h4 class="gamma ag-title">Property</h4>
					<div class="agreement-info ag-property">
						<span class="address line"><%= @property.house_number %>, <%= @property.street_address %>,</span>
						<% unless @property.street_address_two.blank? %>
						<span class="address line"><%= @property.street_address_two %>,</span>
						<% end %>
						<span class="address line"><%= @property.city %>,</span>
						<span class="address line"><%= @property.postcode.upcase %></span>
					</div>
			</div>
			<div class="agreement">
				<h4 class="gamma ag-title">Start Date</h4>
					<%= f.text_field :rent_start_date, :class => "agreement-info ag-start-date calendar-date date" %>
			</div>
				
			<div class="agreement">
				<h4 class="gamma ag-title">Tenancy Term</h4>
					<%= f.select( :tenancy_term, {"1 month" => "one_monthly", "6 months" => "half_year", "1 year" => "yearly"}, :class => "agreement-info ag-end-date") %>		
			</div>

			<div class="agreement">
				<h4 class="gamma ag-title">Rent Frequency</h4>
					<span class="frequency">
						<%= f.select( :rent_frequency, {"Weekly" => "weekly", "Fortnightly" => "fortnightly", "Monthly" => "monthly"}, :class => "agreement-info ag-frequency") %>
					</span>	
			</div>
			<div class="agreement currency">
				<h4 class="gamma ag-title">Rent Amount</h4>
					<%= f.fields_for :payment do |builder| %>
						<%= builder.text_field :rent_amount, :class => "agreement-info ag-amount amount" %>
					<% end %>
			</div>	
		</div>
</article>

<hr class="divider" />

<article class="tenant-extras">
	<div class="contract">
		<%= f.file_field :tenancy_agreement, :id => "hidden-pdf", :style => "visibility:hidden" %>
			<div title="Upload Agreement" class="pdf-download" id="visible-pdf">
				<span class="icon-pdf"></span>
					Upload Tenancy Agreement
			</div>
	</div>
	<div class="totals">
		<div class="total deposit">
			<h3 class="gamma total-title">Deposit:</h3>
				<%= f.fields_for :payment do |builder| %>
					<%= builder.text_field :deposit, :class => "total-amount" %>
						<%= f.label :deposit_received, "Deposit Received:", :class => "gamma total-title deposit-received" %>
					<%= builder.check_box :deposit_received %>
				<% end %>
		</div>
	</div>				
</article>
	<%= f.submit "Save changes", :class => "button submit" %>				
	<% end %>
	</div>
</section>

app/views/tenants/new.html.erb
<%= render 'property_details' %>

<section class="current-tenants">
	<div class="current-tenant">
		
	<h3 class="center">Enter new tenant's details</h3>
	<%= form_for @tenant, :html => { :class => "tenant-details" }, :url => property_tenants_path(@property) do |f| %>
	<%= render "shared/tenant_error_message", :target => @tenant %>
		
	<fieldset>
		<%= f.label :first_name, "First Name:" %>
		<%= f.text_field :first_name %>
	</fieldset>
	<fieldset>
		<%= f.label :second_name, "Surname:" %>
		<%= f.text_field :second_name %>
	</fieldset>
	<fieldset>
		<%= f.label :email, "Email:" %>
		<%= f.text_field :email %>
	</fieldset>
	<fieldset>
		<%= f.label :house_phone, "House Phone:" %>
		<%= f.text_field :house_phone %>
	</fieldset>
	<fieldset>
		<%= f.label :mobile_phone, "Mobile Phone:" %>
		<%= f.text_field :mobile_phone %>
	</fieldset>

<hr class="divider" />

<article class="tenant-agreement">
	<h3 class="beta agreement-title">Renting Agreement</h3>
		<div class="agreement-list">

			<div class="agreement">
				<h4 class="gamma ag-title">Start Date</h4>
					<%= f.text_field :rent_start_date, :class => "agreement-info ag-start-date calendar-date date" %>
			</div>
				
			<div class="agreement">
				<h4 class="gamma ag-title">Tenancy Term</h4>
					<%= f.select( :tenancy_term, {"1 month" => "one_monthly", "6 months" => "half_year", "1 year" => "yearly"}, :class => "agreement-info ag-end-date") %>		
			</div>

			<div class="agreement">
				<h4 class="gamma ag-title">Rent Frequency</h4>
					<span class="frequency">
						<%= f.select( :rent_frequency, {"Weekly" => "weekly", "Fortnightly" => "fortnightly", "Monthly" => "monthly"}, :class => "agreement-info ag-frequency") %>
					</span>	
			</div>

			<div class="agreement currency">
				<h4 class="gamma ag-title">Rent Amount</h4>
					<%= f.fields_for :payment do |builder| %>
						<%= builder.text_field :rent_amount, :class => "agreement-info ag-amount amount" %>
					<% end %>
			</div>
		</div>
</article>

<hr class="divider" />

<article class="tenant-extras">
	<div class="contract">
		<%= f.file_field :tenancy_agreement, :id => "hidden-pdf", :style => "visibility:hidden" %>
			<div title="Upload Agreement" class="pdf-download" id="visible-pdf">
				<span class="icon-pdf"></span>
					Upload Tenancy Agreement
			</div>
	</div>

	<div class="totals">
		<div class="total deposit">
			<h3 class="gamma total-title">Deposit:</h3>
				<%= f.fields_for :payment do |builder| %>
					<%= builder.text_field :deposit, :class => "total-amount" %>
						<%= f.label :deposit_received, "Deposit Received:", :class => "gamma total-title deposit-received" %>
					<%= builder.check_box :deposit_received %>
				<% end %>
		</div>
	</div>

</article>
	<%= f.submit "Save changes", :class => "button submit" %>				
	<% end %>
	</div>
</section>

app/views/tenants/show.html.erb
<section class="current-tenants">
	<div class="current-tenants-management">
		<h2 class="beta section-title">Tenant Details</h2>
	</div>

	<div class="current-tenant">
	<article class="tenant-details">
	<div class="tenant">
		<h3 class="tenant-name"><%= full_name(@tenant) %></h3>
		<p class="tenant-email"><%= mail_to(@tenant.email) %></p>
		<p class="tenant-phone"><%= @tenant.house_phone %></p>
		<p class="tenant-phone"><%= @tenant.mobile_phone %></p>
		<%= link_to "[Delete]", property_tenant_path(@property, @tenant), :class => "edit edit-tenant-details", :method => 'delete', :data => { :confirm => "Are you sure?" } %>
		<%= link_to "[Edit]", edit_property_tenant_path(@property, @tenant), :class => "edit edit-tenant-details", :title => "Edit tenant details" %>
	</div>
	</article>

	<hr class="divider" />
	
	<article class="tenant-agreement">
		<h3 class="beta agreement-title">Renting Agreement</h3>
		<div class="agreement-list">
		<div class="agreement">
			<h4 class="gamma ag-title">Property</h4>
				<div class="agreement-info ag-property">
					<%= link_to property_path(@property) do %>
					<span class="address line"><%= @property.house_number %></span>
					<span class="address line"><%= @property.street_address %></span>
					<span class="address line"><%= @property.street_address_two %></span>
					<span class="address line"><%= @property.city %></span>
					<span class="address line"><%= @property.postcode.upcase %></span>
					<% end %>
				</div>
		</div>

		<div class="agreement">
			<h4 class="gamma ag-title">Start Date</h4>
			<div class="agreement-info ag-start-date">
				<span class="date"><%= @tenant.rent_start_date %></span>
			</div>
		</div>

		<div class="agreement">
			<h4 class="gamma ag-title">End Date</h4>
			<div class="agreement-info ag-end-date">
				<span class="date"><%= @tenant.monthly.to_date if @tenant.tenancy_term == "one_monthly" %></span>
				<span class="date"><%= @tenant.half_year.to_date if @tenant.tenancy_term == "half_year" %></span>
				<span class="date"><%= @tenant.yearly.to_date if @tenant.tenancy_term == "yearly" %></span>				
			</div>
		</div>

		<div class="agreement">
			<h4 class="gamma ag-title">Rent Frequency</h4>
			<div class="agreement-info ag-frequency">
				<span class="frequency"><%= @tenant.rent_frequency.capitalize %></span>
			</div>
		</div>

		<div class="agreement">
			<h4 class="gamma ag-title">Rent Amount</h4>
			<div class="agreement-info ag-amount">
				<span class="amount"><%= number_to_currency @tenant.payment.rent_amount %></span>
				<% if @tenant.rent_frequency == "fortnightly" %>
					<span class="due">Due in: <%= @tenant.rent_due_in %> days</span>
				<% end %>
				<% if @tenant.rent_frequency == "monthly" %>
					<span class="due">Due in: <%= @tenant.rent_due_in_monthly %> days</span>
				<% end %>
			</div>
		</div>
	</div>
	</article>
	
	<hr class="divider" />

	<article class="tenant-extras">
		<div class="contract">
			<% unless @tenant.tenancy_agreement.blank? %>
			<%= link_to @tenant.tenancy_agreement.url, :class => "pdf-download" do %>
				<span class="icon-pdf"></span><%= "View Tenancy Agreement" %>
			<% end %>
			<% end %>
		</div>
		<div class="totals">
			<div class="total">
				<h3 class="gamma total-title ver">Deposit:</h3>
				<span class="total-amount"><%= number_to_currency @tenant.payment.deposit %></span>
			</div>
		<div class="total">
			<h3 class="gamma total-title ver">Deposit received:</h3>
			<span class="total-amount"><%= deposit_true_or_false(@tenant) %></span>
		</div>
	</article>
</div>
</section>