config/routes.rb
Lodgerapp::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	devise_for :users, :skip => [:registrations] 
	as :user do
		get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
		put 'users' => 'devise/registrations#update', :as => 'user_registration'
	end
	root to: "properties#index"

	resources :properties do
		get 'vacant', :on => :collection
		resources :tenants
	end

	resources :tenants do
		get 'current', :on => :collection
	end
end

app/models/property.rb
class Property < ActiveRecord::Base
	belongs_to :user
	has_many :tenants, :dependent => :destroy
	has_many :payments, :through => :tenants
	
	validates 	:postcode, :city, :presence => true

	validate :at_least_one_street_address_must_be_present

	private

	def at_least_one_street_address_must_be_present
		if (street_address.blank? and street_address_two.blank?)
			errors.add(:base, "At least one street address must be present")
		end
	end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	protect_from_forgery with: :exception
	
	before_filter :authenticate_user!

	def index
		@properties = current_user.properties
	end

	def new
		@property = Property.new
	end

	def create
		@property = Property.new(app_params)
		@property.user = current_user
		if @property.save
			flash[:success] = render_to_body(:partial => "shared/new_property_message")
			redirect_to @property
		else
			render('new')
		end
	end

	def show
		@property = Property.find(params[:id])
	end

	def edit
		@property = Property.find(params[:id])
	end

	def update
		@property = Property.find(params[:id])
		if @property.update_attributes(app_params)
			redirect_to(@property)
		else
			render('edit')
		end
	end

	def destroy
		@property = Property.find(params[:id])
		@property.destroy
		redirect_to properties_path
	end

	def vacant
		@properties = current_user.properties.order(:postcode)
	end

	def app_params
		params.require(:property).permit(:house_number, :street_address, :street_address_two, :city, :postcode)
	end
end

app/helpers/properties_helper.rb
module PropertiesHelper
	def full_address(property)
		[property.house_number, property.street_address, property.street_address_two, property.city, property.postcode.upcase,].compact.reject(&:blank?).join(', ')
	end

	def list_tenant_by_name(property)
		property.tenants.all().map {|p| link_to("#{p.first_name} #{p.second_name}", property_tenant_path(property, p), {:class => "tenant"} )}.to_sentence.html_safe
	end

	def tenant_rent_weekly(property)
	for tenant in property.tenants
		if tenant.rent_frequency == "weekly"
		a = tenant.rent_due_in_weekly
		end
	end
 	a
	end

	def tenant_rent_fortnightly(property)
	for tenant in property.tenants.reject
		if tenant.rent_frequency == "fortnightly"
		a = tenant.rent_due_in_fortnightly
		end
	end
	a
	end

	def tenant_rent_monthly(property)
	for tenant in property.tenants.reject
		if tenant.rent_frequency == "monthly"
		a = tenant.rent_due_in_monthly
		end
	end
	a
	end
	def tenant_rent_min(property)
		[tenant_rent_weekly(property), tenant_rent_fortnightly(property), tenant_rent_monthly(property)].compact.min
	end

	def rent_class(property)
		if tenant_rent_min(property) <= 7
		return 'rent due-soon'
		else
		return 'rent due-distance'
	end
	end

	def vacant_count(property)
		current_user.properties.count - occupied_count(property)
	end

	def occupied_count(property)
		current_user.tenants.where("tenants.id IS NOT NULL").count
	end
end

app/views/properties/edit.html.erb
<div class="session">
<h2>Edit property details</h2>

<%= form_for @property do |f| %>
<%= render "shared/property_error_message", :target => @property %>
<fieldset>
	<%= f.text_field :house_number, :placeholder => "Number" %>
</fieldset>
<fieldset>
	<%= f.text_field :street_address, :placeholder => "Street 1" %>
</fieldset>
<fieldset>
	<%= f.text_field :street_address_two, :placeholder => "Street 2" %>
</fieldset>
<fieldset>
	<%= f.text_field :city, :placeholder => "City" %>
</fieldset>
<fieldset>
	<%= f.text_field :postcode, :placeholder => "Postcode" %>
</fieldset>
	<%= f.submit "Save changes", :class => "button" %>
<% end %>
</div>

app/views/properties/index.html.erb
<div class="two-thirds main-content">
	<div class="properties-management">
		<h2 class="beta properties-filter-title">Properties:</h2>
			<ul class="menu properties-filter">
				<li class="active">
					<span class="filter">Occupied</a><span class="property-amount"> (<%= occupied_count(@properties) %>)</span>
				</li>
				<li>
					<%= link_to vacant_properties_path(@property), :class => "filter" do %>
					Vacant<span class="property-amount"> (<%= vacant_count(@properties) %>)</span>
					<% end %>
				</li>
			</ul>
	<% unless @properties.empty? %>
		<%=link_to new_property_path(@property), :class => "button new-property" do %>
		<span class="icon add-new"></span><%= "New property" %>
		<% end %>
	<% end %>
	</div>

	<section class="properties list">
	<% @properties.each do |property| if property.tenants.any? %>
		<article class="property">
			<div class="property-details">
				<div class="property-info">
					<h3 class="gamma property-address"><%= link_to truncate(full_address(property), :length => 45), property_path(property) %></h3>
						<div class="menu tenants">
							<%= list_tenant_by_name(property) %>
						</div>
				</div>

			<div class="rent-info">
			<% unless property.tenants.empty? %>
				<span class="rent-due">Rent due in:</span>
				<span class="<%= rent_class(property) %>"><%= pluralize(tenant_rent_min(property), "day") %></span>
			<% end %>
			</div>
      		</div>
		</article>
	<% end %>
	<% end %>
	</section>

	<% if @properties.empty? %>
	<p class="property-empty">You don't have any properties yet. <%= link_to new_property_path(@property), :class => "button new-property" do %>
	<span class="icon add-new"></span><%= "Add one now" %>
	<% end %></p>
	<% end %>
</div>

app/views/properties/new.html.erb
<div class="session">
<h2>Add a new property</h2>

<%= form_for @property, :html => {:multipart => true} do |f| %>
<%= render "shared/property_error_message", :target => @property %>
<fieldset>
	<%= f.text_field :house_number, :placeholder => "Number" %>
</fieldset>
<fieldset>
	<%= f.text_field :street_address, :placeholder => "Street 1" %>
</fieldset>
<fieldset>
	<%= f.text_field :street_address_two, :placeholder => "Street 2" %>
</fieldset>
<fieldset>
	<%= f.text_field :city, :placeholder => "City" %>
</fieldset>
<fieldset>
	<%= f.text_field :postcode, :placeholder => "Postcode" %>
</fieldset>
	<%= f.button :class => "button-wrap button" do %>
		<span class="icon add-new"></span><%= "Add property" %>
	<% end %>
<% end %>
</div>

app/views/properties/show.html.erb
<section class="full-property-details">
	<article class="property-address-list">
		<h2 class="beta page-title">Property Details</h2>

		<span class="address-line"><% unless @property.house_number.blank? %><%= @property.house_number %>,<% end %> <% unless @property.street_address.blank? %><%= @property.street_address %>,<% end%></span>
		<% unless @property.street_address_two.blank? %>
		<span class="address-line"><%= @property.street_address_two %>,</span>
		<% end %>
		<span class="address-line"><%= @property.city %>,</span>
		<span class="address-line"><%= @property.postcode.upcase %></span>

		<%= link_to "[Edit]", edit_property_path(@property), :class => "edit edit-address", :title => "Edit address" %>
		<%= link_to "[Delete]", property_path(@property), :class => "edit", :method => 'delete', :confirm => "Are you sure?" %>
	</article>
</section>

<hr class="divider" />

<% unless @property.tenants.blank? %>
<section class="current-tenants">
	<div class="current-tenants-management">
		<h2 class="beta section-title">Current <%= pluralize_without_count(@property.tenants.count, 'Tenant') %></h2>
		<%= link_to new_property_tenant_path(@property, @tenant), :class => "button new-property" do %>
		<span class="icon add-new"></span><%= "New tenant" %>
		<% end %>
	</div>
<% @property.tenants.each do |tenant| %>
<div class="current-tenant">
	<article class="tenant-details">
	<div class="tenant">
		<h3 class="tenant-name"><%= link_to tenant.first_name + " " + tenant.second_name, property_tenant_path(tenant.property, tenant.id) %></h3>
		<p class="tenant-email"><%= mail_to(tenant.email) %></p>
		<p class="tenant-phone"><%= tenant.house_phone %></p>
		<p class="tenant-phone"><%= tenant.mobile_phone %></p>
		<%= link_to "[Delete]", property_tenant_path(@property, tenant), :class => "edit edit-tenant-details", :title => "Delete tenant", :data => { :confirm => "Are you sure?" } %>
		<%= link_to "[Edit]", edit_property_tenant_path(@property, tenant), :class => "edit edit-tenant-details", :title => "Edit tenant details" %>
	</div>
	</article>
                
<hr class="divider" />
        
	<article class="tenant-agreement">
	<h3 class="beta agreement-title">Renting Agreement</h3>
	<div class="agreement-list">
		<div class="agreement">
		<h4 class="gamma ag-title">Property</h4>
			<div class="agreement-info ag-property">
			<span class="address line"><%= @property.house_number %>, <%= @property.street_address %>,</span>
			<span class="address line"><%= @property.street_address_two %>,</span>
			<span class="address line"><%= @property.city %>,</span>
			<span class="address line"><%= @property.postcode.upcase %></span>
			</div>
		</div>
                        
		<div class="agreement">
		<h4 class="gamma ag-title">Start Date</h4>
		<div class="agreement-info ag-start-date">
			<span class="date"><%= tenant.rent_start_date %></span>
		</div>
	</div>

	<div class="agreement">
		<h4 class="gamma ag-title">End Date</h4>
			<div class="agreement-info ag-end-date">
				<span class="date"><%= tenant.one_monthly.to_date if tenant.tenancy_term == "one_monthly" %></span>
				<span class="date"><%= tenant.half_year.to_date if tenant.tenancy_term == "half_year" %></span>
				<span class="date"><%= tenant.yearly.to_date if tenant.tenancy_term == "yearly" %></span>
 			</div>
	</div>

	<div class="agreement">
		<h4 class="gamma ag-title">Rent Frequency</h4>
			<div class="agreement-info ag-frequency">
				<span class="frequency"><%= tenant.rent_frequency.capitalize %></span>
			</div>
	</div>

	<div class="agreement">
		<h4 class="gamma ag-title">Rent Amount</h4>
		<div class="agreement-info ag-amount">
			<span class="amount"><%= number_to_currency tenant.payment.rent_amount %></span>
		<% if tenant.rent_frequency == "weekly" %>
			<span class="due">Due in: <%= pluralize(tenant.rent_due_in_weekly, "day") %></span>
		<% end %>
		<% if tenant.rent_frequency == "fortnightly" %>
			<span class="due">Due in: <%= pluralize(tenant.rent_due_in_fortnightly, "day") %></span>
		<% end %>
		<% if tenant.rent_frequency == "monthly" %>
			<span class="due">Due in: <%= pluralize(tenant.rent_due_in_monthly, "day") %></span>
		<% end %>
		</div>
	</div>                               
 </article>
        
<hr class="divider" />

	<article class="tenant-extras">
	<div class="contract">
		<% unless tenant.tenancy_agreement.blank? %>
		<%= link_to tenant.tenancy_agreement.url, :class => "pdf-download" do %>
		<span class="icon-pdf"></span><%= "View Tenancy Agreement" %>
		<% end %>
		<% end %>
	</div>

	<div class="totals">
	<% unless tenant.payment.deposit.blank? %>
		<div class="total">
		<h3 class="gamma total-title ver">Deposit:</h3>
			<span class="total-amount"><%= number_to_currency tenant.payment.deposit %></span>
		</div>
	<% end %>
		<div class="total">
		<h3 class="gamma total-title ver">Deposit received:</h3>
			<span class="total-amount"><%= deposit_true_or_false(tenant) %></span>
		</div>
	</div>
	</article>                                                                    
	</div>
</section>
<% end %>

<% else %>

<p class="property-empty">This property currently has no tenants. <%= link_to new_property_tenant_path(@property, @tenant), :class => "button new-property" do %>
	<span class="icon add-new"></span><%= "Add one now" %>
	<% end %></p>

<% end %>

app/views/properties/vacant.html.erb
<div class="two-thirds main-content">
	<div class="properties-management">
		<h2 class="beta properties-filter-title">Properties:</h2>
			<ul class="menu properties-filter">
				<li>
					<%= link_to properties_path(@property), :class => "filter" do %>
					Occupied<span class="property-amount"> (<%= occupied_count(@properties) %>)</span>
					<% end %>
				</li>
				<li class="active">
					<span class="filter">Vacant <span class="property-amount"> (<%= vacant_count(@properties) %>)</span></span>
				</li>
			</ul>
	<% unless @properties.blank? %>
		<%=link_to new_property_path(@property), :class => "button new-property" do %>
		<span class="icon add-new"></span><%= "New property" %>
		<% end %>
	<% end %>
	</div>

	<section class="properties list">
	<% @properties.each do |property| unless property.tenants.any? %>
		<article class="property">
			<div class="property-details">
				<div class="vacant property-info">
					<h3 class="gamma property-address"><%= link_to truncate(full_address(property), :length => 45), property_path(property) %></h3>
						<div class="menu tenants-vacant">
							Vacant
						</div>
				</div>

				<div class="rent-info">
				<%= link_to new_property_tenant_path(property), :class => "button-light new-property" do %>
					<span class="icon add-new-dark"></span><%= "Add Tenant" %>
				<% end %>
			</div>
      		</div>
		</article>
	</section>
	<% end %>
	<% end %>

	<% if @properties.empty? %>
	<p class="property-empty">You don't have any properties yet. <%= link_to new_property_path(@property), :class => "button new-property" do %>
	<span class="icon add-new"></span><%= "Add one now" %>
	<% end %></p>
	<% end %>
</div>