config/routes.rb
Lodgerapp::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
	devise_for :users, :skip => [:registrations] 
	as :user do
		get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
		put 'users' => 'devise/registrations#update', :as => 'user_registration'
	end
	root to: "properties#index"

	resources :properties do
		get 'vacant', :on => :collection
		resources :tenants
	end

	resources :tenants do
		get 'current', :on => :collection
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Lodgerapp</title>
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<!-- Google Fonts -->
<link href='https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700,300italic,400italic,500italic,700italic' rel='stylesheet' type='text/css'>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-48901497-1', 'lodgerapp.co.uk');
ga('send', 'pageview');
</script>
<!--[if lt IE 9]>
<script type="text/javascript" src="js/html5shiv.js"></script>
<script type="text/javascript" src="js/css3-mediaqueries.js"></script>
<%= stylesheet_link_tag    "ie8", "data-turbolinks-track" => true %>
<![endif]-->
</head>
<body>
<header class="main-header">
	<div class="wrapper">
		<nav class="main-nav">
			<%= link_to image_tag("lodger-app-logo.png", :alt => "Lodger App", :class => "logo"), properties_url %>
			<%= tabs_tag :open_tabs => { :class => "menu main-menu" } do |tab| %>
			<%= tab.property 'Property Overview', properties_url, :title => "Property Overview" %>
			<%= tab.tenant 'Tenants', current_tenants_path(@tenant), :title => "Tenants" %>
			<% end %>
		</nav>
		<% if user_signed_in? %>
		<nav class="account-info">
			<ul class="account-nav">
		  	<li class="account-nav__link">
					<%= link_to "Hi #{current_user.email}", edit_user_registration_path, :class=> "account-link", :title => "My Account" %>
			<ul class="account-nav__flyout">
				<li><%= link_to "Edit account", edit_user_registration_path, :title => "Edit Account", :class=> "account-links" %></li>
				<li><%= link_to "Logout", destroy_user_session_path, :method => :delete, :class=> "account-links" %></li>
			</ul>
				</li>
			</ul>
		</nav>
		<% else %>
		<nav class="account-info">
			<%= link_to "Login", new_user_session_path, :class=> "account-login" %>
		</nav>
		<% end %>
	</div>
</header>
<div class="wrapper">
<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name == :notice ? "success" : "error" %>">
		<a class="close" data-dismiss="alert">&#215;</a>
		<%= content_tag :div, msg, :class => "flash_#{name}" %>
	</div>
<% end %>

<%= yield %>
</div>
</body>
</html>